// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: acronis • component: button-icon
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "borderColor": {
        "button-icon-secondary-container-active": "light-dark(rgb(255 0 255 / 0), rgb(255 0 255 / 0))",
        "button-icon-secondary-container-disabled": "light-dark(rgb(214 228 245), rgb(6 54 121))",
        "button-icon-secondary-container-hover": "light-dark(rgb(255 0 255 / 0), rgb(255 0 255 / 0))",
        "button-icon-secondary-container-idle": "light-dark(rgb(214 228 245), rgb(6 54 121))"
      },
      "fill": {
        "button-icon-global-active": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "button-icon-global-disabled": "light-dark(rgb(214 228 245), rgb(6 54 121))",
        "button-icon-global-hover": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "button-icon-global-idle": "light-dark(rgb(23 99 207), rgb(48 125 232))"
      },
      "spacing": {
        "button-icon-global-container-height": "32px",
        "button-icon-global-container-padding-x": "8px",
        "button-icon-global-icon-size": "16px",
        "button-icon-secondary-container-border-width": "1px"
      },
      "borderRadius": {
        "button-icon-global-container-border-radius": "4px"
      }
    },
  },
};
