// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: acronis • component: input
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "textColor": {
        "input-global-active": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "input-global-disabled": "light-dark(rgb(175 178 182), rgb(85 89 94))",
        "input-global-hover": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "input-global-idle": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "input-global-required": "light-dark(rgb(226 54 54), rgb(226 54 54))",
        "input-content-value-active": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "input-content-value-disabled": "light-dark(rgb(175 178 182), rgb(85 89 94))",
        "input-content-value-hover": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "input-content-value-idle": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "input-error-error": "light-dark(rgb(226 54 54), rgb(226 54 54))",
        "input-normal-description": "light-dark(rgb(109 114 120), rgb(109 114 120))"
      },
      "borderColor": {
        "input-error-box-active": "light-dark(rgb(226 54 54), rgb(226 54 54))",
        "input-error-box-hover": "light-dark(rgb(226 54 54), rgb(226 54 54))",
        "input-error-box-idle": "light-dark(rgb(226 54 54), rgb(226 54 54))",
        "input-normal-box-active": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "input-normal-box-disabled": "light-dark(rgb(214 228 245), rgb(6 54 121))",
        "input-normal-box-hover": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "input-normal-box-idle": "light-dark(rgb(214 228 245), rgb(6 54 121))"
      },
      "fontFamily": {
        "input-global-label-text-style": "Inter, system-ui, sans-serif",
        "input-global-required-text-style": "Inter, system-ui, sans-serif",
        "input-content-text-style": "Inter, system-ui, sans-serif",
        "input-error-error-text-style": "Inter, system-ui, sans-serif",
        "input-normal-description-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "input-global-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-global-required-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-content-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-error-error-text-style": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-normal-description-text-style": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "input-global-box-border-width": "1px",
        "input-global-box-gap": "12px",
        "input-global-box-height": "32px",
        "input-global-box-padding-x": "12px",
        "input-global-box-padding-y": "4px",
        "input-global-container-gap": "4px",
        "input-global-container-width-min": "224px",
        "input-global-container-label-gap": "4px"
      },
      "borderRadius": {
        "input-global-box-border-radius": "4px"
      }
    },
  },
};
