// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: acronis • component: menu-item
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "menu-item-global-active": "light-dark(rgb(214 228 245), rgb(6 54 121))",
        "menu-item-global-focus": "light-dark(rgb(190 215 244), rgb(11 66 142))",
        "menu-item-global-hover": "light-dark(rgb(238 242 247), rgb(0 32 77))",
        "menu-item-global-idle": "light-dark(rgb(255 255 255 / 0), rgb(255 255 255 / 0))"
      },
      "textColor": {
        "menu-item-global-active": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-global-focus": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-global-hover": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-global-idle": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "fill": {
        "menu-item-global-active": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "menu-item-global-focus": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "menu-item-global-hover": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "menu-item-global-idle": "light-dark(rgb(23 99 207), rgb(48 125 232))"
      },
      "spacing": {
        "menu-item-global-units-gap-x": "8px",
        "menu-item-global-units-gap-y": "4px",
        "menu-item-global-units-height-min": "40px",
        "menu-item-global-units-padding-icon": "4px",
        "menu-item-global-units-padding-x": "16px",
        "menu-item-global-units-padding-y": "8px",
        "menu-item-global-units-width-min": "128px"
      }
    },
  },
};
