// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: acronis • component: menu-item
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "textColor": {
        "menu-item-link-active": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-link-description-false-active": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "menu-item-link-description-false-focus": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "menu-item-link-description-false-hover": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "menu-item-link-description-false-idle": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "menu-item-link-description-true-description-active": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-link-description-true-description-focus": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-link-description-true-description-hover": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-link-description-true-description-idle": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-link-description-true-active": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "menu-item-link-description-true-focus": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "menu-item-link-description-true-hover": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "menu-item-link-description-true-idle": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "menu-item-link-focus": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-link-hover": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-link-idle": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-static-description-false-active": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-static-description-false-focus": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-static-description-false-hover": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-static-description-false-idle": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-static-description-true-active": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-static-description-true-focus": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-static-description-true-hover": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-static-description-true-idle": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "fill": {
        "menu-item-global-active": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "menu-item-global-focus": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "menu-item-global-hover": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "menu-item-global-idle": "light-dark(rgb(23 99 207), rgb(48 125 232))"
      },
      "fontFamily": {
        "menu-item-link-description-false-label-text-style": "Inter, system-ui, sans-serif",
        "menu-item-link-description-true-description-text-style": "Inter, system-ui, sans-serif",
        "menu-item-link-description-true-label-text-style": "Inter, system-ui, sans-serif",
        "menu-item-static-description-false-label-text-style": "Inter, system-ui, sans-serif",
        "menu-item-static-description-true-description-text-style": "Inter, system-ui, sans-serif",
        "menu-item-static-description-true-label-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "menu-item-link-description-false-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "500"
          }
        ],
        "menu-item-link-description-true-description-text-style": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "menu-item-link-description-true-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "500"
          }
        ],
        "menu-item-static-description-false-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "menu-item-static-description-true-description-text-style": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "menu-item-static-description-true-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "500"
          }
        ]
      },
      "spacing": {
        "menu-item-global-container-gap": "8px",
        "menu-item-global-container-height-description-min": "56px",
        "menu-item-global-container-height-min": "40px",
        "menu-item-global-container-padding-x": "16px",
        "menu-item-global-container-padding-y": "8px",
        "menu-item-global-container-width-min": "128px",
        "menu-item-global-container-content-gap": "0px",
        "menu-item-global-container-left-padding-y": "4px",
        "menu-item-global-icon-size": "16px"
      }
    },
  },
};
