// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: acronis • component: sidebar
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "sidebar-primary-active": "light-dark(rgb(23 99 207), rgb(48 125 232))",
        "sidebar-primary-focus": "light-dark(rgb(190 215 244), rgb(11 66 142))",
        "sidebar-primary-hover": "light-dark(rgb(3 43 99), rgb(226 235 245))",
        "sidebar-primary-idle": "light-dark(rgb(255 255 255 / 0), rgb(255 255 255 / 0))",
        "sidebar-secondary-active": "light-dark(rgb(214 228 245), rgb(6 54 121))",
        "sidebar-secondary-focus": "light-dark(rgb(190 215 244), rgb(11 66 142))",
        "sidebar-secondary-hover": "light-dark(rgb(238 242 247), rgb(0 32 77))",
        "sidebar-secondary-idle": "light-dark(rgb(255 255 255 / 0), rgb(255 255 255 / 0))"
      },
      "textColor": {
        "sidebar-primary-active": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "sidebar-primary-focus": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "sidebar-primary-hover": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "sidebar-primary-idle": "light-dark(rgb(255 255 255 / 0.6), rgb(0 0 0 / 0.6))",
        "sidebar-secondary-active": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "sidebar-secondary-focus": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "sidebar-secondary-hover": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "sidebar-secondary-idle": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "fill": {
        "sidebar-secondary-external-link": "light-dark(rgb(23 99 207), rgb(48 125 232))"
      },
      "spacing": {
        "sidebar-global-units-icon-padding": "4px",
        "sidebar-global-units-item-gap-x": "8px",
        "sidebar-global-units-item-gap-y": "4px",
        "sidebar-global-units-item-height-min": "40px",
        "sidebar-global-units-item-padding-y": "8px",
        "sidebar-global-units-item-primary-padding-x": "12px",
        "sidebar-global-units-item-secaondary-padding-x": "8px",
        "sidebar-global-units-item-width-min": "128px",
        "sidebar-global-units-tag-padding-y": "2px"
      }
    },
  },
};
