// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: acronis • component: switch
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "textColor": {
        "switch-container-active": "light-dark(rgb(70 185 89), rgb(36 143 54))",
        "switch-container-disabled": "light-dark(rgb(248 250 252), rgb(0 21 51))",
        "switch-label": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "switch-toggle-disabled": "light-dark(rgb(214 228 245), rgb(6 54 121))"
      },
      "borderColor": {
        "switch-container-disabled": "light-dark(rgb(214 228 245), rgb(6 54 121))"
      },
      "spacing": {
        "switch-container-border": "1px",
        "switch-container-height": "16px",
        "switch-container-padding-x": "2px",
        "switch-container-padding-y": "2px",
        "switch-container-width": "32px",
        "switch-toggle-size": "12px",
        "switch-units-gap": "8px"
      },
      "borderRadius": {
        "switch-container-radius": "999px",
        "switch-toggle-radius": "999px"
      }
    },
  },
};
