// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: acronis • component: tag
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "tag-ai": "light-dark(rgb(249 245 251), rgb(82 20 82))",
        "tag-critical": "light-dark(rgb(255 240 230), rgb(102 46 0))",
        "tag-danger": "light-dark(rgb(253 237 237), rgb(108 19 19))",
        "tag-info": "light-dark(rgb(238 242 247), rgb(0 32 77))",
        "tag-neutral": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "tag-success": "light-dark(rgb(238 247 239), rgb(3 58 17))",
        "tag-warning": "light-dark(rgb(255 249 229), rgb(77 55 0))"
      },
      "textColor": {
        "tag-ai": "light-dark(rgb(130 23 130), rgb(250 209 250))",
        "tag-critical": "light-dark(rgb(153 69 0), rgb(190 113 38))",
        "tag-danger": "light-dark(rgb(152 27 27), rgb(251 218 218))",
        "tag-info": "light-dark(rgb(6 54 121), rgb(214 228 245))",
        "tag-neutral": "light-dark(rgb(61 63 67), rgb(125 132 148))",
        "tag-success": "light-dark(rgb(15 87 33), rgb(56 150 66))",
        "tag-warning": "light-dark(rgb(138 99 0), rgb(255 238 178))"
      },
      "borderColor": {
        "tag-critical": "light-dark(rgb(255 204 153), rgb(178 80 0))",
        "tag-danger": "light-dark(rgb(248 195 195), rgb(173 31 31))",
        "tag-info": "light-dark(rgb(190 215 244), rgb(11 66 142))",
        "tag-neutral": "light-dark(rgb(201 204 207), rgb(73 76 80))",
        "tag-success": "light-dark(rgb(178 229 187), rgb(26 102 38))",
        "tag-warning": "light-dark(rgb(255 227 128), rgb(178 128 0))"
      },
      "spacing": {
        "tag-units-border": "1px",
        "tag-units-gap": "4px",
        "tag-units-height-lg": "24px",
        "tag-units-height-sm": "20px",
        "tag-units-padding-x": "8px",
        "tag-units-width-max": "256px",
        "tag-units-width-min": "32px"
      },
      "borderRadius": {
        "tag-units-radius": "999px"
      }
    },
  },
};
