// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: orange_tsukaeru_helpox • component: Carousel
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "spacing": {
        "carousel-dialog-list-indicator-gap": "6px"
      }
    },
  },
};
