// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: brand-b • component: breadcrumb
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "textColor": {
        "breadcrumb-text-link-idle": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "breadcrumb-text-link-hover": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "breadcrumb-text-link-active": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "breadcrumb-text-value": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "fill": {
        "breadcrumb-icon-chevron": "light-dark(rgb(201 204 207), rgb(73 76 80))"
      },
      "spacing": {
        "breadcrumb-units-gap": "4px",
        "breadcrumb-units-padding-x": "16px"
      }
    },
  },
};
