// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: brand-b • component: sidebar
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "sidebar-primary-active": "light-dark(rgb(4 73 67), rgb(209 240 237))",
        "sidebar-primary-focus": "light-dark(rgb(70 185 175), rgb(31 122 115))",
        "sidebar-primary-hover": "light-dark(rgb(3 58 54), rgb(226 245 244))",
        "sidebar-primary-idle": "light-dark(rgb(255 255 255 / 0), rgb(255 255 255 / 0))",
        "sidebar-secondary-active": "light-dark(rgb(209 240 237), rgb(4 73 67))",
        "sidebar-secondary-focus": "light-dark(rgb(178 230 225), rgb(10 92 85))",
        "sidebar-secondary-hover": "light-dark(rgb(226 245 244), rgb(3 58 54))",
        "sidebar-secondary-idle": "light-dark(rgb(255 255 255 / 0), rgb(255 255 255 / 0))"
      },
      "textColor": {
        "sidebar-primary-active": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "sidebar-primary-focus": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "sidebar-primary-hover": "light-dark(rgb(255 255 255), rgb(0 0 0))",
        "sidebar-primary-idle": "light-dark(rgb(255 255 255 / 0.6), rgb(0 0 0 / 0.6))",
        "sidebar-secondary-active": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "sidebar-secondary-focus": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "sidebar-secondary-hover": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "sidebar-secondary-idle": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "fill": {
        "sidebar-secondary-external-link": "light-dark(rgb(255 255 255 / 0.6), rgb(0 0 0 / 0.6))"
      },
      "spacing": {
        "sidebar-global-units-icon-padding": "4px",
        "sidebar-global-units-item-gap-x": "8px",
        "sidebar-global-units-item-gap-y": "4px",
        "sidebar-global-units-item-height-min": "40px",
        "sidebar-global-units-item-padding-y": "8px",
        "sidebar-global-units-item-primary-padding-x": "8px",
        "sidebar-global-units-item-secaondary-padding-x": "8px",
        "sidebar-global-units-item-width-min": "128px",
        "sidebar-global-units-tag-padding-y": "2px"
      }
    },
  },
};
