// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: telstra • component: Calendar
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "calendar-container": "light-dark(rgb(255 255 255), rgb(31 32 34))",
        "calendar-item-active": "light-dark(rgb(73 76 80), rgb(81 157 246))",
        "calendar-item-hover": "light-dark(rgb(236 237 238), rgb(37 38 40))",
        "calendar-item-idle": "light-dark(transparent, transparent)"
      },
      "textColor": {
        "calendar-value-active": "light-dark(rgb(255 255 255), rgb(255 255 255))",
        "calendar-value-disabled": "light-dark(rgb(175 178 182), rgb(85 89 94))",
        "calendar-value-idle-primary": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "calendar-value-idle-secondary": "light-dark(rgb(97 101 107), rgb(135 139 146))"
      },
      "borderColor": {
        "calendar-body-border": "light-dark(rgb(215 217 219), rgb(61 63 67))",
        "calendar-container-border": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "calendar-header-border": "light-dark(rgb(215 217 219), rgb(61 63 67))",
        "calendar-item-border-active": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "calendar-item-border-hover": "light-dark(transparent, transparent)",
        "calendar-item-border-idle": "light-dark(transparent, transparent)"
      },
      "fontFamily": {
        "calendar-value-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "calendar-value-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "calendar-body-border-width": "1px",
        "calendar-body-padding-x": "12px",
        "calendar-body-padding-y": "12px",
        "calendar-container-border-width": "1px",
        "calendar-header-border-width": "1px",
        "calendar-header-gap": "16px",
        "calendar-header-padding-x": "12px",
        "calendar-header-padding-y": "12px",
        "calendar-item-height-min": "32px",
        "calendar-item-width-min": "32px"
      },
      "borderRadius": {
        "calendar-container-border-radius": "4px"
      }
    },
  },
};
