// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: telstra • component: Toast
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "toast-global-container-background": "light-dark(rgb(255 255 255), rgb(31 32 34))"
      },
      "textColor": {
        "toast-global-content-text-container-description": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "toast-global-content-text-container-title": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "borderColor": {
        "toast-critical-border-color": "light-dark(rgb(240 112 0), rgb(255 153 51))",
        "toast-danger-border-color": "light-dark(rgb(217 38 38), rgb(237 94 94))",
        "toast-info-border-color": "light-dark(rgb(19 84 174), rgb(121 158 210))",
        "toast-success-border-color": "light-dark(rgb(36 143 54), rgb(107 199 122))",
        "toast-warning-border-color": "light-dark(rgb(229 164 0), rgb(255 196 0))"
      },
      "fontFamily": {
        "toast-global-content-text-container-description-text-style": "Inter, system-ui, sans-serif",
        "toast-global-content-text-container-title-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "toast-global-content-text-container-description-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "toast-global-content-text-container-title-text-style": [
          "18px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "toast-global-container-border-width": "1px",
        "toast-global-container-gap": "8px",
        "toast-global-container-padding-x": "16px",
        "toast-global-container-padding-y": "8px",
        "toast-global-container-status-width": "6px",
        "toast-global-container-width-min": "384px",
        "toast-global-content-actions-container-gap-x": "16px",
        "toast-global-content-actions-container-gap-y": "8px",
        "toast-global-content-actions-container-padding-x": "0px",
        "toast-global-content-actions-container-padding-y": "8px",
        "toast-global-content-gap": "0px",
        "toast-global-content-padding-x": "0px",
        "toast-global-content-padding-y": "0px",
        "toast-global-content-text-container-gap": "0px",
        "toast-global-content-text-container-padding-x": "0px",
        "toast-global-content-text-container-padding-y": "4px",
        "toast-global-icon-padding-x": "4px",
        "toast-global-icon-padding-y": "8px",
        "toast-global-icon-size": "16px"
      },
      "borderRadius": {
        "toast-global-container-border-radius": "8px"
      },
      "boxShadow": {
        "toast-global-container": "0px 16px 32px 0px light-dark(rgb(0 0 0 / 0.102), rgb(0 0 0 / 0.4))"
      }
    },
  },
};
