// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: yellow-1c • component: InputNumPicker
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "input-num-picker-global-box-disabled": "light-dark(rgb(244 245 245), rgb(24 25 27))",
        "input-num-picker-global-box-hover": "light-dark(rgb(255 255 255), rgb(31 32 34))",
        "input-num-picker-global-box-idle": "light-dark(rgb(255 255 255), rgb(31 32 34))"
      },
      "textColor": {
        "input-num-picker-global-label-disabled": "light-dark(rgb(175 178 182), rgb(85 89 94))",
        "input-num-picker-global-label-hover": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "input-num-picker-global-label-idle": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "input-num-picker-global-required": "light-dark(rgb(226 54 54), rgb(229 77 77))",
        "input-num-picker-global-value-disabled": "light-dark(rgb(175 178 182), rgb(85 89 94))",
        "input-num-picker-global-value-hover": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "input-num-picker-global-value-idle": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "borderColor": {
        "input-num-picker-normal-box-border-color-disabled": "light-dark(rgb(215 217 219), rgb(61 63 67))",
        "input-num-picker-normal-box-border-color-hover": "light-dark(rgb(109 114 120), rgb(109 114 120))",
        "input-num-picker-normal-box-border-color-idle": "light-dark(rgb(215 217 219), rgb(61 63 67))"
      },
      "fontFamily": {
        "input-num-picker-global-label-text-style": "Inter, system-ui, sans-serif",
        "input-num-picker-global-required-text-style": "Inter, system-ui, sans-serif",
        "input-num-picker-global-value-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "input-num-picker-global-label-text-style": [
          "14px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-num-picker-global-required-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "input-num-picker-global-value-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "input-num-picker-global-box-border-width": "1px",
        "input-num-picker-global-box-gap": "12px",
        "input-num-picker-global-box-height": "32px",
        "input-num-picker-global-box-padding-x": "12px",
        "input-num-picker-global-box-padding-y": "4px",
        "input-num-picker-global-container-gap": "4px",
        "input-num-picker-global-container-width-min": "128px",
        "input-num-picker-global-container-label-gap": "4px"
      },
      "borderRadius": {
        "input-num-picker-global-box-border-radius": "4px"
      }
    },
  },
};
