// Generated by packages/ui-spec/scripts/generate-stories.ts
// Run `pnpm --filter @acronis-platform/ui-spec generate:stories` to regenerate.
import type { Meta, StoryObj } from '@storybook/react-vite';

import { CardWidgetCarousel } from '../card-widget-carousel';

const meta = {
  title: 'Widgets/CardWidgetCarousel',
  component: CardWidgetCarousel,
} satisfies Meta<typeof CardWidgetCarousel>;

export default meta;
type Story = StoryObj<typeof meta>;

export const States: Story = {
  render: () => (
    <div style={{ width: 608 }}>
      <CardWidgetCarousel>
        <div className="flex h-32 w-72 shrink-0 items-center justify-center rounded-lg border border-[var(--ui-border-on-surface-border)] bg-[var(--ui-background-surface-primary)] text-sm text-[var(--ui-text-on-surface-secondary)]">
          Card 1
        </div>
        <div className="flex h-32 w-72 shrink-0 items-center justify-center rounded-lg border border-[var(--ui-border-on-surface-border)] bg-[var(--ui-background-surface-primary)] text-sm text-[var(--ui-text-on-surface-secondary)]">
          Card 2
        </div>
      </CardWidgetCarousel>
    </div>
  ),
};
