// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: light-gray • component: ButtonGroup
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "button-group-global-box-active": "light-dark(rgb(228 229 231), rgb(48 50 54))",
        "button-group-global-box-hover": "light-dark(rgb(236 237 238), rgb(37 38 40))",
        "button-group-global-box-idle": "light-dark(transparent, transparent)"
      },
      "borderColor": {
        "button-group-global-container-border-color": "light-dark(rgb(215 217 219), rgb(61 63 67))",
        "button-group-global-separator": "light-dark(rgb(215 217 219), rgb(61 63 67))"
      },
      "spacing": {
        "button-group-global-box-height": "32px",
        "button-group-global-box-padding-x": "12px",
        "button-group-global-box-padding-y": "8px",
        "button-group-global-container-border-width": "1px",
        "button-group-global-separator-border-width": "1px"
      },
      "borderRadius": {
        "button-group-global-container-border-radius": "4px"
      }
    },
  },
};
