// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: deep_sky_itkontoret • component: AlertRibbon
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "alert-ribbon-critical-background": "light-dark(rgb(255 240 230), rgb(77 35 0))",
        "alert-ribbon-danger-background": "light-dark(rgb(253 237 237), rgb(87 15 15))",
        "alert-ribbon-info-background": "light-dark(rgb(238 242 247), rgb(26 47 77))",
        "alert-ribbon-success-background": "light-dark(rgb(238 247 239), rgb(3 58 17))",
        "alert-ribbon-warning-background": "light-dark(rgb(255 249 229), rgb(102 73 0))"
      },
      "textColor": {
        "alert-ribbon-global-carousel-counter-text": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "alert-ribbon-global-content-description": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "borderColor": {
        "alert-ribbon-critical-divider": "light-dark(rgb(255 204 153), rgb(153 69 0))",
        "alert-ribbon-danger-divider": "light-dark(rgb(248 195 195), rgb(151 27 27))",
        "alert-ribbon-info-divider": "light-dark(rgb(190 215 244), rgb(41 81 122))",
        "alert-ribbon-success-divider": "light-dark(rgb(178 229 187), rgb(26 102 38))",
        "alert-ribbon-warning-divider": "light-dark(rgb(255 227 128), rgb(178 128 0))"
      },
      "fontFamily": {
        "alert-ribbon-global-carousel-counter-text-style": "Inter, system-ui, sans-serif",
        "alert-ribbon-global-content-description-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "alert-ribbon-global-carousel-counter-text-style": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "500"
          }
        ],
        "alert-ribbon-global-content-description-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "alert-ribbon-global-carousel-gap": "8px",
        "alert-ribbon-global-container-gap": "32px",
        "alert-ribbon-global-container-height": "48px",
        "alert-ribbon-global-container-padding-xleft": "16px",
        "alert-ribbon-global-container-padding-xright": "0px",
        "alert-ribbon-global-container-padding-y": "0px",
        "alert-ribbon-global-container-width-min": "512px",
        "alert-ribbon-global-content-gap": "8px",
        "alert-ribbon-global-icon-size": "16px"
      }
    },
  },
};
