// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: default • component: SegmentControl
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "segment-control-box-icon-active": "light-dark(rgb(226 235 245), rgb(48 50 54))",
        "segment-control-box-icon-hover": "light-dark(rgb(226 235 245), rgb(48 50 54))",
        "segment-control-box-icon-idle": "light-dark(rgb(238 242 247), rgb(46 47 50))",
        "segment-control-container": "light-dark(rgb(238 242 247), rgb(46 47 50))",
        "segment-control-item-active": "light-dark(rgb(255 255 255), rgb(31 32 34))",
        "segment-control-item-hover": "light-dark(transparent, transparent)",
        "segment-control-item-idle": "light-dark(transparent, transparent)"
      },
      "textColor": {
        "segment-control-value-active": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "segment-control-value-hover": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "segment-control-value-idle": "light-dark(rgb(109 114 120), rgb(109 114 120))"
      },
      "borderColor": {
        "segment-control-box-icon-border-color": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "segment-control-container-border-color": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "segment-control-item-border-active": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "segment-control-item-border-hover": "light-dark(transparent, transparent)",
        "segment-control-item-border-idle": "light-dark(transparent, transparent)"
      },
      "fontFamily": {
        "segment-control-value-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "segment-control-value-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ]
      },
      "spacing": {
        "segment-control-box-icon-border-width": "1px",
        "segment-control-box-icon-height": "40px",
        "segment-control-box-icon-width": "32px",
        "segment-control-container-border-width": "1px",
        "segment-control-container-gap": "8px",
        "segment-control-container-height": "40px",
        "segment-control-container-padding-x": "4px",
        "segment-control-container-padding-y": "4px",
        "segment-control-item-border-width": "1px",
        "segment-control-item-gap": "8px",
        "segment-control-item-height": "32px",
        "segment-control-item-padding-x": "12px",
        "segment-control-item-padding-y": "4px"
      },
      "borderRadius": {
        "segment-control-container-border-radius": "8px",
        "segment-control-item-border-radius": "4px"
      }
    },
  },
};
