// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: default • component: SideSheet
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "side-sheet-container": "light-dark(rgb(248 250 252), rgb(24 25 27))",
        "side-sheet-header": "light-dark(rgb(255 255 255), rgb(31 32 34))"
      },
      "textColor": {
        "side-sheet-header-title": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "borderColor": {
        "side-sheet-header-border-color": "light-dark(rgb(214 228 245), rgb(48 50 54))"
      },
      "fontFamily": {
        "side-sheet-header-title-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "side-sheet-header-title-text-style": [
          "24px",
          {
            "lineHeight": "32px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "side-sheet-header-border-width": "1px",
        "side-sheet-header-gap": "16px",
        "side-sheet-header-padding-x": "16px",
        "side-sheet-header-padding-y": "16px"
      }
    },
  },
};
