// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: default • component: Timer
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "timer-container": "light-dark(rgb(255 255 255), rgb(31 32 34))"
      },
      "textColor": {
        "timer-value": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "borderColor": {
        "timer-container-border": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "timer-content-box-divider": "light-dark(rgb(214 228 245), rgb(48 50 54))"
      },
      "fontFamily": {
        "timer-value-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "timer-value-text-style": [
          "18px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ]
      },
      "spacing": {
        "timer-container-border-width": "1px",
        "timer-container-height": "32px",
        "timer-content-box-divider-width": "1px",
        "timer-content-box-padding-x": "12px"
      },
      "borderRadius": {
        "timer-container-radius": "4px"
      }
    },
  },
};
