// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: virtuozzo • component: Stepper
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "stepper-item-completed-container-active": "light-dark(rgb(228 229 231), rgb(48 50 54))",
        "stepper-item-completed-container-focus-ring": "light-dark(rgb(190 215 244), rgb(81 157 246))",
        "stepper-item-completed-container-hover": "light-dark(rgb(236 237 238), rgb(37 38 40))",
        "stepper-item-completed-container-idle": "light-dark(transparent, transparent)",
        "stepper-item-current-container": "light-dark(rgb(228 229 231), rgb(48 50 54))",
        "stepper-item-future-container": "light-dark(transparent, transparent)"
      },
      "textColor": {
        "stepper-item-completed-label": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "stepper-item-current-label": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "stepper-item-future-label": "light-dark(rgb(175 178 182), rgb(85 89 94))",
        "stepper-breakpoint-default-label": "light-dark(rgb(97 101 107), rgb(135 139 146))",
        "stepper-breakpoint-default-value": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "borderColor": {
        "stepper-item-current-container-border-color": "light-dark(rgb(215 217 219), rgb(61 63 67))"
      },
      "fontFamily": {
        "stepper-item-global-container-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "stepper-item-global-container-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "500"
          }
        ]
      },
      "spacing": {
        "stepper-item-global-container-gap": "8px",
        "stepper-item-global-container-padding-l": "8px",
        "stepper-item-global-container-padding-r": "16px",
        "stepper-item-global-container-padding-x": "8px",
        "stepper-item-global-container-padding-y": "8px",
        "stepper-item-current-container-border-width": "1px",
        "stepper-breakpoint-default-line-gap": "4px",
        "stepper-breakpoint-lg-container-gap": "8px"
      },
      "borderRadius": {
        "stepper-item-global-container-border-radius": "8px"
      }
    },
  },
};
