// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: virtuozzo • component: Timeline
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "spacing": {
        "timeline-gap": "16px"
      }
    },
  },
};
