import * as React from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { DotRedIcon } from '@acronis-platform/icons-react/stroke-multi';

import { cn } from '@/lib/utils';

// ChatMenuItemCollapsed — one row of the chat rail while the rail is collapsed
// (Figma "ChatMenuItemCollapsed", node 7329:25084). It is icon-only: the 48px
// rail leaves no room for the label, so the whole row is the 16px glyph plus an
// optional red alert dot.
//
// Tokens come from the dedicated `--ui-chat-*` tier generated by
// @acronis-platform/tokens-pd (its `@import` is added to `src/styles/index.css`;
// this is the tier's first consumer). Nothing is reimplemented from
// SidebarSecondary — the Figma node binds the `components/Chat/*` variable group
// and that is what is referenced here.
//
// Geometry (all from the design's own variables):
//   height          -> --ui-chat-menu-item-height              (40px)
//   width           -> --ui-chat-menu-item-collapsed-max-width (48px)
//   padding-x       -> --ui-chat-menu-item-padding-x           (16px)
//   gap             -> --ui-chat-menu-item-expanded-gap        (8px)
//   start border    -> --ui-chat-global-border-width/-color
//   icon color      -> --ui-chat-menu-item-icon-color
//
// The Figma frame draws that 1px seam as a LEFT border; it is the rail's
// inline-start edge, so it is expressed logically (`border-inline-start-*`) and
// mirrors under `dir="rtl"`.
//
// `variant` has a single value, `idle` — the state this design was signed off
// with. The Figma component set also carries `hover` / `active` / `focused`
// siblings, but those are pure INTERACTION states, not API values: they are
// wired below as `hover:` / `active:` / `focus-visible:` so each state resolves
// its own token (a brand may give them distinct values) without inventing prop
// values the design never asked for. Adding a real second `variant` value stays
// a purely additive change.
//
// The design's remaining variables have no `--ui-*` counterpart in tokens-pd and
// follow the kit's existing conventions instead: the focus ring's `stroke/width-3`
// (3px) / `radius/radius-4` (4px) as `ring-[3px]` + `rounded-sm` (the same
// treatment every other component uses), the 16px `components/Icon/_global/sm/size`
// as `size-4`, and `components/Icon/_global/sm/stroke` (1.6px) which
// @acronis-platform/icons-react already bakes into its `size={16}` artwork.
const chatMenuItemCollapsedVariants = cva(
  'relative flex h-[var(--ui-chat-menu-item-height)] w-[var(--ui-chat-menu-item-collapsed-max-width)] shrink-0 cursor-pointer items-center gap-[var(--ui-chat-menu-item-expanded-gap)] border-solid [border-inline-start-color:var(--ui-chat-global-border-color)] [border-inline-start-width:var(--ui-chat-global-border-width)] px-[var(--ui-chat-menu-item-padding-x)] transition-colors focus-visible:rounded-sm focus-visible:outline-none focus-visible:ring-[3px] focus-visible:ring-inset focus-visible:ring-[var(--ui-focus-primary)]',
  {
    variants: {
      variant: {
        idle: 'bg-[var(--ui-chat-menu-item-color-idle)] hover:bg-[var(--ui-chat-menu-item-color-hover)] active:bg-[var(--ui-chat-menu-item-color-active)]',
      },
    },
    defaultVariants: {
      variant: 'idle',
    },
  }
);

export interface ChatMenuItemCollapsedProps
  extends
    React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof chatMenuItemCollapsedVariants> {
  /**
   * The 16px glyph that stands in for the item while the rail is collapsed.
   * Mono icons inherit `--ui-chat-menu-item-icon-color` via `currentColor`.
   */
  icon?: React.ReactNode;
  /**
   * Show the red alert dot over the glyph's top-end corner (the shipped
   * `DotRedIcon`). Purely decorative — the alert must also be conveyed in the
   * `aria-label` this control is given.
   */
  hasAlert?: boolean;
}

/**
 * A collapsed (icon-only) chat rail menu item. Because there is no visible
 * label, provide an `aria-label` (or `aria-labelledby`) so the control has an
 * accessible name — and fold the alert into it when `hasAlert` is set.
 */
const ChatMenuItemCollapsed = React.forwardRef<
  HTMLButtonElement,
  ChatMenuItemCollapsedProps
>(({ className, variant, icon, hasAlert = false, type, ...props }, ref) => (
  <button
    ref={ref}
    type={type ?? 'button'}
    className={cn(chatMenuItemCollapsedVariants({ variant }), className)}
    {...props}
  >
    <span className="relative flex size-4 shrink-0 items-center justify-center text-[var(--ui-chat-menu-item-icon-color)] [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0">
      {icon}
      {hasAlert && (
        // Figma parks the 16px DotRed box at (27, 4) inside the 48x40 root while
        // the 16px glyph box sits at (17, 12) — i.e. offset (+10px, -8px) from
        // the glyph's top-start corner, so its 8px dot straddles the glyph's
        // top-end corner. Anchoring to the glyph (rather than the root) keeps
        // that relationship, and `start-2.5` mirrors under `dir="rtl"`.
        <DotRedIcon
          size={16}
          aria-hidden="true"
          className="absolute -top-2 start-2.5"
        />
      )}
    </span>
  </button>
));
ChatMenuItemCollapsed.displayName = 'ChatMenuItemCollapsed';

export { ChatMenuItemCollapsed, chatMenuItemCollapsedVariants };
